version: "3"
services:
  hub:
    image: tritonuas/hub
    environment:
      - INTEROP_IP=127.0.0.1
      - INTEROP_PORT=8000
      - INTEROP_USER=ucsdauvsi
      - INTEROP_PASS=tritons
      - MAV_DEVICE=tcp:mavproxy:14551
      - MAV_OUTPUT1=""
        # - MAV-OUTPUT2=udp:192.168.1.14:14550
        # - MAV-OUTPUT3=udp:192.168.1.8:14550
      # - MAV-OUTPUT4=""
      # - MAV-OUTPUT5=""
      - HUB_PATH=/go/src/github.com/tritonuas/hub
    volumes:
      - missions:/go/src/github.com/tritonuas/hub/missions
    depends_on: 
      - mavproxy
      - influxdb_cli
      - influxdb
    links: 
      - mavproxy
      - influxdb
  influxdb:
    image: influxdb:2.0-alpine
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"
  grafana:
    image: grafana/grafana:7.5.5
    depends_on:
      - hub 
    environment: 
      - GF_USERS_DEFAULT_THEME=light
      - GF_USERS_HOME_PAGE=/dashboards
      # - GF_INSTALL_PLUGINS=briangann-gauge-panel
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=500ms
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
  influxdb_cli:
    links:
      - influxdb
    image: influxdb:2.0-alpine
    entrypoint: > 
      influx setup 
      --bucket mavlink 
      -o TritonUAS 
      -t influxdbToken 
      --username=tritons 
      --password=tritonuas 
      --host=http://influxdb:8086 
      -f
    restart: on-failure:10
    depends_on:
      - influxdb
  mavproxy:
    image: tritonuas/mavproxy
    ports:
      - "5761:5762"
      - "14551:14551"
    environment:
      - "MASTER=--master=/dev/ttyUSB0"
      - "OUT1=--out=udp:172.17.0.1:14550"
      - "OUT2=--out=tcpin:mavproxy:14551"
      - "OUT3=--out=udp:192.168.1.14:14555"
      - "OUT4=--out=udp:192.168.1.8:14556"
      # - "OUT5=--out=udp:mavproxy:5762"
      # - OUT6=
      # - OUT7=
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
volumes:
  grafana_data:
  influxdb_data:
  missions:
