version: "3"
services:
  hub:
    image: tritonuas/hub
    environment:
      - INTEROP_IP=172.17.0.1
      - INTEROP_PORT=8000
      - INTEROP_USER=ucsdauvsi
      - INTEROP_PASS=tritons
      - MAV_DEVICE=tcp:sitl:5760
      - MAV_OUTPUT1=""
      - MAV_OUTPUT2=""
      - MAV_OUTPUT3=""
      - MAV_OUTPUT4=""
      - MAV_OUTPUT5=""
      - INFLUXDB_BUCKET=mavlink
      - INFLUXDB_ORG=TritonUAS
      - INFLUXDB_TOKEN=influxdbToken
      - HUB_PATH=/go/src/github.com/tritonuas/hub
    volumes:
      - missions:/go/src/github.com/tritonuas/hub/missions
    logging:
      driver: journald
  influxdb:
    image: influxdb:2.0-alpine
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    logging:
      driver: journald
  grafana:
    image: grafana/grafana:7.5.5
    depends_on:
      - influxdb
    environment: 
      - GF_USERS_DEFAULT_THEME=dark
      - GF_USERS_HOME_PAGE=/dashboards
      - GF_INSTALL_PLUGINS=briangann-gauge-panel
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=500ms
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    logging:
      driver: journald
  influxdb_cli:
    links:
      - influxdb
    depends_on:
      - influxdb
    image: influxdb:2.0-alpine
    entrypoint: > 
      influx setup 
      --bucket mavlink 
      --org TritonUAS 
      --token influxdbToken 
      --username tritons 
      --password tritonuas 
      --host http://influxdb:8086 
      --force
    restart: on-failure:10
    logging:
      driver: journald
  sitl:
    image: tritonuas/plane.rascal
    environment:
      - "SITL_HOME=38.145844,-76.42638,8,0"
      - SITL_SPEEDUP=1
    ports:
      - "5760:5760"
    volumes:
      - sitl:/app/logs
    logging:
      driver: none
  mavproxy:
    image: tritonuas/mavproxy
    ports:
      - "5761:5762"
      - "14551:14551"
    environment:
      - "MASTER=--master=tcp:sitl:5760"
      - "OUT1=--out=udp:172.17.0.1:14550"
      - "OUT2=--out=tcpin:mavproxy:14551"
      # - "OUT2=--out=udp:mavproxy:14555"
      # - "OUT3=--out=udp:mavproxy:14556"
      # - "OUT4=--out=tcpin:mavproxy:5761"
      # - "OUT5=--out=udp:mavproxy:5762"
      # - OUT6=
      # - OUT7=
    restart: always
    logging:
      driver: journald
volumes:
  grafana_data:
  influxdb_data:
  missions:
  sitl:
