version: "3"
services:
  hub:
    image: tritonuas/hub
    # ports:
    #   - '5000:5000'
    environment:
      - INTEROP_IP=172.17.0.1
      - INTEROP_PORT=8000
      - INTEROP_USER=ucsdauvsi
      - INTEROP_PASS=tritons
      - MAV_DEVICE=tcp:localhost:5760
      - MAV_OUTPUT1=udp:localhost:14553
      - MAV_OUTPUT2=""
      - MAV_OUTPUT3=""
      - MAV_OUTPUT4=""
      - MAV_OUTPUT5=""
      - INFLUXDB_BUCKET=mavlink
      - INFLUXDB_ORG=TritonUAS
      - INFLUXDB_TOKEN=influxdbToken
      - HUB_PATH=/go/src/github.com/tritonuas/hub
    volumes:
      - missions:/go/src/github.com/tritonuas/hub/missions
    depends_on: 
      # - mavproxy
      - influxdb_cli
      - influxdb
    # links:
      # - mavproxy
      # - influxdb
    # logging:
    #   driver: none
    network_mode: "host"
      
  influxdb:
    image: influxdb:2.0-alpine
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
    # logging:
    #   driver: none 
  grafana:
    image: grafana/grafana:7.5.5
    depends_on:
      - hub 
    environment: 
      - GF_USERS_DEFAULT_THEME=dark
      - GF_USERS_HOME_PAGE=/dashboards
      - GF_INSTALL_PLUGINS=briangann-gauge-panel
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=500ms
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    # logging:
    #   driver: none 
  influxdb_cli:
    links:
      - influxdb
    depends_on:
      - influxdb
    image: influxdb:2.0-alpine
    entrypoint: > 
      influx setup 
      --bucket mavlink 
      --org TritonUAS 
      --token influxdbToken 
      --username tritons 
      --password tritonuas 
      --host http://influxdb:8086 
      --force
    # entrypoint: influx org list
    restart: on-failure:20
    # logging:
      # driver: none 
  sitl:
    image: tritonuas/plane.rascal
    environment:
      - "SITL_HOME=38.145844,-76.42638,8,0"
      - SITL_SPEEDUP=1
    # ports:
    #   - "5760:5760"
    volumes:
      - sitl:/app/logs
    # logging:
    #   driver: none
    network_mode: host
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
volumes:
  grafana_data:
  influxdb_data:
  missions:
  sitl:
