// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interop/mission_report.proto

package interop

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MissionReportStatus struct {
	MissionWaypoints     []*DistanceStatus `protobuf:"bytes,1,rep,name=mission_waypoints,json=missionWaypoints" json:"mission_waypoints,omitempty"`
	AirdropPos           *DistanceStatus   `protobuf:"bytes,2,opt,name=airdrop_pos,json=airdropPos" json:"airdrop_pos,omitempty"`
	EmergentPos          *DistanceStatus   `protobuf:"bytes,3,opt,name=emergent_pos,json=emergentPos" json:"emergent_pos,omitempty"`
	StationaryObstacles  []*DistanceStatus `protobuf:"bytes,4,rep,name=stationary_obstacles,json=stationaryObstacles" json:"stationary_obstacles,omitempty"`
	MovingObstacles      []*DistanceStatus `protobuf:"bytes,5,rep,name=moving_obstacles,json=movingObstacles" json:"moving_obstacles,omitempty"`
	Hz                   float32           `protobuf:"fixed32,6,opt,name=hz" json:"hz,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *MissionReportStatus) Reset()         { *m = MissionReportStatus{} }
func (m *MissionReportStatus) String() string { return proto.CompactTextString(m) }
func (*MissionReportStatus) ProtoMessage()    {}
func (*MissionReportStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_mission_report_1a1b3a80310cd043, []int{0}
}
func (m *MissionReportStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MissionReportStatus.Unmarshal(m, b)
}
func (m *MissionReportStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MissionReportStatus.Marshal(b, m, deterministic)
}
func (dst *MissionReportStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissionReportStatus.Merge(dst, src)
}
func (m *MissionReportStatus) XXX_Size() int {
	return xxx_messageInfo_MissionReportStatus.Size(m)
}
func (m *MissionReportStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MissionReportStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MissionReportStatus proto.InternalMessageInfo

func (m *MissionReportStatus) GetMissionWaypoints() []*DistanceStatus {
	if m != nil {
		return m.MissionWaypoints
	}
	return nil
}

func (m *MissionReportStatus) GetAirdropPos() *DistanceStatus {
	if m != nil {
		return m.AirdropPos
	}
	return nil
}

func (m *MissionReportStatus) GetEmergentPos() *DistanceStatus {
	if m != nil {
		return m.EmergentPos
	}
	return nil
}

func (m *MissionReportStatus) GetStationaryObstacles() []*DistanceStatus {
	if m != nil {
		return m.StationaryObstacles
	}
	return nil
}

func (m *MissionReportStatus) GetMovingObstacles() []*DistanceStatus {
	if m != nil {
		return m.MovingObstacles
	}
	return nil
}

func (m *MissionReportStatus) GetHz() float32 {
	if m != nil {
		return m.Hz
	}
	return 0
}

type DistanceStatus struct {
	ClosestDist          float32  `protobuf:"fixed32,1,opt,name=closest_dist,json=closestDist" json:"closest_dist,omitempty"`
	CurrentDist          float32  `protobuf:"fixed32,2,opt,name=current_dist,json=currentDist" json:"current_dist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DistanceStatus) Reset()         { *m = DistanceStatus{} }
func (m *DistanceStatus) String() string { return proto.CompactTextString(m) }
func (*DistanceStatus) ProtoMessage()    {}
func (*DistanceStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_mission_report_1a1b3a80310cd043, []int{1}
}
func (m *DistanceStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DistanceStatus.Unmarshal(m, b)
}
func (m *DistanceStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DistanceStatus.Marshal(b, m, deterministic)
}
func (dst *DistanceStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DistanceStatus.Merge(dst, src)
}
func (m *DistanceStatus) XXX_Size() int {
	return xxx_messageInfo_DistanceStatus.Size(m)
}
func (m *DistanceStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_DistanceStatus.DiscardUnknown(m)
}

var xxx_messageInfo_DistanceStatus proto.InternalMessageInfo

func (m *DistanceStatus) GetClosestDist() float32 {
	if m != nil {
		return m.ClosestDist
	}
	return 0
}

func (m *DistanceStatus) GetCurrentDist() float32 {
	if m != nil {
		return m.CurrentDist
	}
	return 0
}

func init() {
	proto.RegisterType((*MissionReportStatus)(nil), "interop.MissionReportStatus")
	proto.RegisterType((*DistanceStatus)(nil), "interop.DistanceStatus")
}

func init() {
	proto.RegisterFile("interop/mission_report.proto", fileDescriptor_mission_report_1a1b3a80310cd043)
}

var fileDescriptor_mission_report_1a1b3a80310cd043 = []byte{
	// 273 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xd1, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc0, 0x71, 0x9a, 0xe9, 0x84, 0xd7, 0x31, 0x67, 0x26, 0xd8, 0x83, 0x87, 0xb9, 0xd3, 0x4e,
	0x13, 0xf4, 0x22, 0x1e, 0x65, 0x27, 0x41, 0x94, 0x0a, 0x7a, 0x2c, 0x59, 0x17, 0xb6, 0xc0, 0x9a,
	0x17, 0xf2, 0xde, 0x94, 0xed, 0x5b, 0xfb, 0x0d, 0xa4, 0x69, 0xca, 0xf4, 0xd2, 0xeb, 0xcb, 0xff,
	0xf7, 0x08, 0x09, 0x5c, 0x1b, 0xcb, 0xda, 0xa3, 0xbb, 0xad, 0x0c, 0x91, 0x41, 0x5b, 0x78, 0xed,
	0xd0, 0xf3, 0xdc, 0x79, 0x64, 0x94, 0x67, 0xf1, 0x74, 0xfa, 0x23, 0x60, 0xfc, 0xd2, 0x14, 0x79,
	0x08, 0xde, 0x59, 0xf1, 0x8e, 0xe4, 0x02, 0x2e, 0x5a, 0xf8, 0xad, 0xf6, 0x0e, 0x8d, 0x65, 0xca,
	0x92, 0x49, 0x6f, 0x96, 0xde, 0x5d, 0xcd, 0x23, 0x9e, 0x2f, 0x0c, 0xb1, 0xb2, 0xa5, 0x6e, 0x4c,
	0x3e, 0x8a, 0xe2, 0xb3, 0x05, 0xf2, 0x01, 0x52, 0x65, 0xfc, 0xca, 0xa3, 0x2b, 0x1c, 0x52, 0x26,
	0x26, 0x49, 0x97, 0x87, 0xd8, 0xbe, 0x21, 0xc9, 0x47, 0x18, 0xe8, 0x4a, 0xfb, 0xb5, 0xb6, 0x1c,
	0x68, 0xaf, 0x9b, 0xa6, 0x6d, 0x5c, 0xdb, 0x67, 0xb8, 0x24, 0x56, 0x6c, 0xd0, 0x2a, 0xbf, 0x2f,
	0x70, 0x49, 0xac, 0xca, 0xad, 0xa6, 0xec, 0xa4, 0xfb, 0xfa, 0xe3, 0x23, 0x7a, 0x6d, 0x8d, 0x7c,
	0x82, 0x51, 0x85, 0x5f, 0xc6, 0xae, 0xff, 0xec, 0x39, 0xed, 0xde, 0x73, 0xde, 0x80, 0xe3, 0x8e,
	0x21, 0x88, 0xcd, 0x21, 0xeb, 0x4f, 0x92, 0x99, 0xc8, 0xc5, 0xe6, 0x30, 0xfd, 0x80, 0xe1, 0x7f,
	0x22, 0x6f, 0x60, 0x50, 0x6e, 0x91, 0x34, 0x71, 0xb1, 0x32, 0xc4, 0x59, 0x12, 0xda, 0x34, 0xce,
	0xea, 0x38, 0x24, 0x3b, 0xef, 0xeb, 0xf7, 0x08, 0x89, 0x88, 0x49, 0x33, 0xab, 0x93, 0x65, 0x3f,
	0xfc, 0xed, 0xfd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x56, 0xc3, 0xf7, 0xfb, 0x01, 0x00,
	0x00,
}
