// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interop/mission_edit.proto

package interop

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MissionName struct {
	MissionName          string   `protobuf:"bytes,1,opt,name=mission_name,json=missionName" json:"mission_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MissionName) Reset()         { *m = MissionName{} }
func (m *MissionName) String() string { return proto.CompactTextString(m) }
func (*MissionName) ProtoMessage()    {}
func (*MissionName) Descriptor() ([]byte, []int) {
	return fileDescriptor_mission_edit_b2d6cc13e67acd59, []int{0}
}
func (m *MissionName) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MissionName.Unmarshal(m, b)
}
func (m *MissionName) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MissionName.Marshal(b, m, deterministic)
}
func (dst *MissionName) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissionName.Merge(dst, src)
}
func (m *MissionName) XXX_Size() int {
	return xxx_messageInfo_MissionName.Size(m)
}
func (m *MissionName) XXX_DiscardUnknown() {
	xxx_messageInfo_MissionName.DiscardUnknown(m)
}

var xxx_messageInfo_MissionName proto.InternalMessageInfo

func (m *MissionName) GetMissionName() string {
	if m != nil {
		return m.MissionName
	}
	return ""
}

type MissionNameList struct {
	MissionNameList      []string `protobuf:"bytes,1,rep,name=mission_name_list,json=missionNameList" json:"mission_name_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MissionNameList) Reset()         { *m = MissionNameList{} }
func (m *MissionNameList) String() string { return proto.CompactTextString(m) }
func (*MissionNameList) ProtoMessage()    {}
func (*MissionNameList) Descriptor() ([]byte, []int) {
	return fileDescriptor_mission_edit_b2d6cc13e67acd59, []int{1}
}
func (m *MissionNameList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MissionNameList.Unmarshal(m, b)
}
func (m *MissionNameList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MissionNameList.Marshal(b, m, deterministic)
}
func (dst *MissionNameList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MissionNameList.Merge(dst, src)
}
func (m *MissionNameList) XXX_Size() int {
	return xxx_messageInfo_MissionNameList.Size(m)
}
func (m *MissionNameList) XXX_DiscardUnknown() {
	xxx_messageInfo_MissionNameList.DiscardUnknown(m)
}

var xxx_messageInfo_MissionNameList proto.InternalMessageInfo

func (m *MissionNameList) GetMissionNameList() []string {
	if m != nil {
		return m.MissionNameList
	}
	return nil
}

type Target struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Latitude             float32  `protobuf:"fixed32,2,opt,name=latitude" json:"latitude,omitempty"`
	Longitude            float32  `protobuf:"fixed32,3,opt,name=longitude" json:"longitude,omitempty"`
	Shape                string   `protobuf:"bytes,4,opt,name=shape" json:"shape,omitempty"`
	Alphanumeric         string   `protobuf:"bytes,5,opt,name=alphanumeric" json:"alphanumeric,omitempty"`
	AlpanumericColor     string   `protobuf:"bytes,6,opt,name=alpanumeric_color,json=alpanumericColor" json:"alpanumeric_color,omitempty"`
	BackgroundColor      string   `protobuf:"bytes,7,opt,name=background_color,json=backgroundColor" json:"background_color,omitempty"`
	Description          string   `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	Orientation          string   `protobuf:"bytes,9,opt,name=orientation" json:"orientation,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}
func (*Target) Descriptor() ([]byte, []int) {
	return fileDescriptor_mission_edit_b2d6cc13e67acd59, []int{2}
}
func (m *Target) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Target.Unmarshal(m, b)
}
func (m *Target) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Target.Marshal(b, m, deterministic)
}
func (dst *Target) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Target.Merge(dst, src)
}
func (m *Target) XXX_Size() int {
	return xxx_messageInfo_Target.Size(m)
}
func (m *Target) XXX_DiscardUnknown() {
	xxx_messageInfo_Target.DiscardUnknown(m)
}

var xxx_messageInfo_Target proto.InternalMessageInfo

func (m *Target) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Target) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Target) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Target) GetShape() string {
	if m != nil {
		return m.Shape
	}
	return ""
}

func (m *Target) GetAlphanumeric() string {
	if m != nil {
		return m.Alphanumeric
	}
	return ""
}

func (m *Target) GetAlpanumericColor() string {
	if m != nil {
		return m.AlpanumericColor
	}
	return ""
}

func (m *Target) GetBackgroundColor() string {
	if m != nil {
		return m.BackgroundColor
	}
	return ""
}

func (m *Target) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Target) GetOrientation() string {
	if m != nil {
		return m.Orientation
	}
	return ""
}

type SitlConfig struct {
	TakeoffDirection     int32    `protobuf:"varint,1,opt,name=takeoff_direction,json=takeoffDirection" json:"takeoff_direction,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SitlConfig) Reset()         { *m = SitlConfig{} }
func (m *SitlConfig) String() string { return proto.CompactTextString(m) }
func (*SitlConfig) ProtoMessage()    {}
func (*SitlConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_mission_edit_b2d6cc13e67acd59, []int{3}
}
func (m *SitlConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SitlConfig.Unmarshal(m, b)
}
func (m *SitlConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SitlConfig.Marshal(b, m, deterministic)
}
func (dst *SitlConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SitlConfig.Merge(dst, src)
}
func (m *SitlConfig) XXX_Size() int {
	return xxx_messageInfo_SitlConfig.Size(m)
}
func (m *SitlConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_SitlConfig.DiscardUnknown(m)
}

var xxx_messageInfo_SitlConfig proto.InternalMessageInfo

func (m *SitlConfig) GetTakeoffDirection() int32 {
	if m != nil {
		return m.TakeoffDirection
	}
	return 0
}

type CompleteMission struct {
	MissionName          string         `protobuf:"bytes,1,opt,name=mission_name,json=missionName" json:"mission_name,omitempty"`
	Mission              *Mission       `protobuf:"bytes,2,opt,name=mission" json:"mission,omitempty"`
	Obstacles            *ObstaclesEdit `protobuf:"bytes,3,opt,name=obstacles" json:"obstacles,omitempty"`
	Sitlconfig           *SitlConfig    `protobuf:"bytes,4,opt,name=sitlconfig" json:"sitlconfig,omitempty"`
	Targets              []*Target      `protobuf:"bytes,5,rep,name=targets" json:"targets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CompleteMission) Reset()         { *m = CompleteMission{} }
func (m *CompleteMission) String() string { return proto.CompactTextString(m) }
func (*CompleteMission) ProtoMessage()    {}
func (*CompleteMission) Descriptor() ([]byte, []int) {
	return fileDescriptor_mission_edit_b2d6cc13e67acd59, []int{4}
}
func (m *CompleteMission) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompleteMission.Unmarshal(m, b)
}
func (m *CompleteMission) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompleteMission.Marshal(b, m, deterministic)
}
func (dst *CompleteMission) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompleteMission.Merge(dst, src)
}
func (m *CompleteMission) XXX_Size() int {
	return xxx_messageInfo_CompleteMission.Size(m)
}
func (m *CompleteMission) XXX_DiscardUnknown() {
	xxx_messageInfo_CompleteMission.DiscardUnknown(m)
}

var xxx_messageInfo_CompleteMission proto.InternalMessageInfo

func (m *CompleteMission) GetMissionName() string {
	if m != nil {
		return m.MissionName
	}
	return ""
}

func (m *CompleteMission) GetMission() *Mission {
	if m != nil {
		return m.Mission
	}
	return nil
}

func (m *CompleteMission) GetObstacles() *ObstaclesEdit {
	if m != nil {
		return m.Obstacles
	}
	return nil
}

func (m *CompleteMission) GetSitlconfig() *SitlConfig {
	if m != nil {
		return m.Sitlconfig
	}
	return nil
}

func (m *CompleteMission) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

func init() {
	proto.RegisterType((*MissionName)(nil), "interop.MissionName")
	proto.RegisterType((*MissionNameList)(nil), "interop.MissionNameList")
	proto.RegisterType((*Target)(nil), "interop.Target")
	proto.RegisterType((*SitlConfig)(nil), "interop.SitlConfig")
	proto.RegisterType((*CompleteMission)(nil), "interop.CompleteMission")
}

func init() {
	proto.RegisterFile("interop/mission_edit.proto", fileDescriptor_mission_edit_b2d6cc13e67acd59)
}

var fileDescriptor_mission_edit_b2d6cc13e67acd59 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xbb, 0x6f, 0xdb, 0x30,
	0x10, 0xc6, 0x21, 0x3b, 0xb6, 0xa3, 0x53, 0x00, 0x39, 0xec, 0x4b, 0x30, 0x3a, 0xa8, 0x9a, 0x9c,
	0x14, 0x70, 0x0b, 0xa7, 0x4b, 0x87, 0x4e, 0x6e, 0xb7, 0x3e, 0x00, 0xb5, 0xbb, 0x41, 0x4b, 0xb4,
	0x73, 0x08, 0x45, 0x0a, 0xe4, 0x79, 0xe8, 0xff, 0xd4, 0xbf, 0xaf, 0x73, 0x21, 0x52, 0xaf, 0x74,
	0xca, 0xa6, 0xfb, 0xbe, 0xdf, 0x77, 0x22, 0x79, 0x07, 0x2b, 0x54, 0x24, 0x8c, 0xae, 0xdf, 0x55,
	0x68, 0x2d, 0x6a, 0xb5, 0x17, 0x25, 0xd2, 0xa6, 0x36, 0x9a, 0x34, 0x5b, 0xb4, 0xde, 0xea, 0x55,
	0x07, 0xe9, 0x83, 0x25, 0x5e, 0x48, 0x61, 0x3d, 0xb1, 0x7a, 0xf1, 0x5f, 0xda, 0xcb, 0xd9, 0x7b,
	0x88, 0xbe, 0x79, 0xe1, 0x3b, 0xaf, 0x04, 0x7b, 0x03, 0x57, 0x5d, 0x77, 0xc5, 0x2b, 0x91, 0x04,
	0x69, 0xb0, 0x0e, 0xf3, 0xa8, 0x1a, 0x90, 0xec, 0x13, 0xc4, 0xa3, 0xc4, 0x57, 0xb4, 0xc4, 0x6e,
	0xe1, 0x7a, 0x9c, 0xda, 0x4b, 0xb4, 0x94, 0x04, 0xe9, 0x74, 0x1d, 0xe6, 0x71, 0xf5, 0x98, 0xcd,
	0xfe, 0x4c, 0x60, 0xfe, 0x8b, 0x9b, 0x93, 0x20, 0xc6, 0xe0, 0x82, 0x7e, 0xd7, 0xdd, 0x4f, 0xdc,
	0x37, 0x5b, 0xc1, 0xa5, 0xe4, 0x84, 0x74, 0x2e, 0x45, 0x32, 0x49, 0x83, 0xf5, 0x24, 0xef, 0x6b,
	0xf6, 0x1a, 0x42, 0xa9, 0xd5, 0xc9, 0x9b, 0x53, 0x67, 0x0e, 0x02, 0x7b, 0x0e, 0x33, 0x7b, 0xcf,
	0x6b, 0x91, 0x5c, 0xb8, 0x76, 0xbe, 0x60, 0x19, 0x5c, 0x71, 0x59, 0xdf, 0x73, 0x75, 0xae, 0x84,
	0xc1, 0x22, 0x99, 0x39, 0xf3, 0x91, 0xc6, 0xde, 0xc2, 0x35, 0x97, 0x75, 0x57, 0xee, 0x0b, 0x2d,
	0xb5, 0x49, 0xe6, 0x0e, 0x5c, 0x8e, 0x8c, 0x5d, 0xa3, 0xb3, 0x1b, 0x58, 0x1e, 0x78, 0xf1, 0x70,
	0x32, 0xfa, 0xac, 0xca, 0x96, 0x5d, 0x38, 0x36, 0x1e, 0x74, 0x8f, 0xa6, 0x10, 0x95, 0xc2, 0x16,
	0x06, 0x6b, 0x42, 0xad, 0x92, 0x4b, 0xff, 0x96, 0x23, 0xa9, 0x21, 0xb4, 0x41, 0xa1, 0x88, 0x3b,
	0x22, 0xf4, 0xc4, 0x48, 0xca, 0x3e, 0x02, 0xfc, 0x44, 0x92, 0x3b, 0xad, 0x8e, 0x78, 0x6a, 0x4e,
	0x4a, 0xfc, 0x41, 0xe8, 0xe3, 0x71, 0x5f, 0xa2, 0x11, 0x85, 0x4b, 0x35, 0xcf, 0x37, 0xcb, 0x97,
	0xad, 0xf1, 0xb9, 0xd3, 0xb3, 0xbf, 0x01, 0xc4, 0x3b, 0x5d, 0xd5, 0x52, 0x90, 0x68, 0x27, 0xf6,
	0x84, 0xf9, 0xb2, 0x5b, 0x58, 0xb4, 0xa5, 0x1b, 0x40, 0xb4, 0x5d, 0x6e, 0xda, 0xd5, 0xd9, 0xb4,
	0x5d, 0xf2, 0x0e, 0x60, 0x1f, 0x20, 0xec, 0xf7, 0xcc, 0x4d, 0x24, 0xda, 0xbe, 0xec, 0xe9, 0x1f,
	0x9d, 0xf3, 0xa5, 0x44, 0xca, 0x07, 0x90, 0xdd, 0x01, 0x58, 0x24, 0x59, 0xb8, 0x3b, 0xb9, 0x71,
	0x45, 0xdb, 0x67, 0x7d, 0x6c, 0xb8, 0x6e, 0x3e, 0xc2, 0xd8, 0x0d, 0x2c, 0xc8, 0xad, 0x8d, 0x4d,
	0x66, 0xe9, 0x74, 0x1d, 0x6d, 0xe3, 0x3e, 0xe1, 0xd7, 0x29, 0xef, 0xfc, 0xc3, 0xdc, 0xad, 0xf6,
	0xdd, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x86, 0x9b, 0xf8, 0x31, 0x03, 0x00, 0x00,
}
