// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interop/mission_edit.proto

/*
Package interop is a generated protocol buffer package.

It is generated from these files:
	interop/mission_edit.proto
	interop/mission.proto
	interop/mission_report.proto
	interop/obstacles.proto
	interop/service.proto
	interop/telemetry.proto

It has these top-level messages:
	MissionName
	MissionNameList
	Target
	SitlConfig
	CompleteMission
	MissionList
	Mission
	GPS
	Waypoint
	FlyZone
	MissionReportStatus
	DistanceStatus
	MovingObstacle
	StationaryObstacle
	Obstacles
	Telemetry
*/
package interop

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MissionName struct {
	MissionName string `protobuf:"bytes,1,opt,name=mission_name,json=missionName" json:"mission_name,omitempty"`
}

func (m *MissionName) Reset()                    { *m = MissionName{} }
func (m *MissionName) String() string            { return proto.CompactTextString(m) }
func (*MissionName) ProtoMessage()               {}
func (*MissionName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MissionName) GetMissionName() string {
	if m != nil {
		return m.MissionName
	}
	return ""
}

type MissionNameList struct {
	MissionNameList []string `protobuf:"bytes,1,rep,name=mission_name_list,json=missionNameList" json:"mission_name_list,omitempty"`
}

func (m *MissionNameList) Reset()                    { *m = MissionNameList{} }
func (m *MissionNameList) String() string            { return proto.CompactTextString(m) }
func (*MissionNameList) ProtoMessage()               {}
func (*MissionNameList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MissionNameList) GetMissionNameList() []string {
	if m != nil {
		return m.MissionNameList
	}
	return nil
}

type Target struct {
	Type             string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Latitude         float32 `protobuf:"fixed32,2,opt,name=latitude" json:"latitude,omitempty"`
	Longitude        float32 `protobuf:"fixed32,3,opt,name=longitude" json:"longitude,omitempty"`
	Shape            string  `protobuf:"bytes,4,opt,name=shape" json:"shape,omitempty"`
	Alphanumeric     string  `protobuf:"bytes,5,opt,name=alphanumeric" json:"alphanumeric,omitempty"`
	AlpanumericColor string  `protobuf:"bytes,6,opt,name=alpanumeric_color,json=alpanumericColor" json:"alpanumeric_color,omitempty"`
	BackgroundColor  string  `protobuf:"bytes,7,opt,name=background_color,json=backgroundColor" json:"background_color,omitempty"`
	Description      string  `protobuf:"bytes,8,opt,name=description" json:"description,omitempty"`
	Orientation      string  `protobuf:"bytes,9,opt,name=orientation" json:"orientation,omitempty"`
}

func (m *Target) Reset()                    { *m = Target{} }
func (m *Target) String() string            { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()               {}
func (*Target) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Target) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Target) GetLatitude() float32 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Target) GetLongitude() float32 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

func (m *Target) GetShape() string {
	if m != nil {
		return m.Shape
	}
	return ""
}

func (m *Target) GetAlphanumeric() string {
	if m != nil {
		return m.Alphanumeric
	}
	return ""
}

func (m *Target) GetAlpanumericColor() string {
	if m != nil {
		return m.AlpanumericColor
	}
	return ""
}

func (m *Target) GetBackgroundColor() string {
	if m != nil {
		return m.BackgroundColor
	}
	return ""
}

func (m *Target) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Target) GetOrientation() string {
	if m != nil {
		return m.Orientation
	}
	return ""
}

type SitlConfig struct {
	TakeoffDirection int32 `protobuf:"varint,1,opt,name=takeoff_direction,json=takeoffDirection" json:"takeoff_direction,omitempty"`
}

func (m *SitlConfig) Reset()                    { *m = SitlConfig{} }
func (m *SitlConfig) String() string            { return proto.CompactTextString(m) }
func (*SitlConfig) ProtoMessage()               {}
func (*SitlConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SitlConfig) GetTakeoffDirection() int32 {
	if m != nil {
		return m.TakeoffDirection
	}
	return 0
}

type CompleteMission struct {
	MissionName string      `protobuf:"bytes,1,opt,name=mission_name,json=missionName" json:"mission_name,omitempty"`
	Mission     *Mission    `protobuf:"bytes,2,opt,name=mission" json:"mission,omitempty"`
	Obstacles   *Obstacles  `protobuf:"bytes,3,opt,name=obstacles" json:"obstacles,omitempty"`
	Sitlconfig  *SitlConfig `protobuf:"bytes,4,opt,name=sitlconfig" json:"sitlconfig,omitempty"`
	Targets     []*Target   `protobuf:"bytes,5,rep,name=targets" json:"targets,omitempty"`
}

func (m *CompleteMission) Reset()                    { *m = CompleteMission{} }
func (m *CompleteMission) String() string            { return proto.CompactTextString(m) }
func (*CompleteMission) ProtoMessage()               {}
func (*CompleteMission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CompleteMission) GetMissionName() string {
	if m != nil {
		return m.MissionName
	}
	return ""
}

func (m *CompleteMission) GetMission() *Mission {
	if m != nil {
		return m.Mission
	}
	return nil
}

func (m *CompleteMission) GetObstacles() *Obstacles {
	if m != nil {
		return m.Obstacles
	}
	return nil
}

func (m *CompleteMission) GetSitlconfig() *SitlConfig {
	if m != nil {
		return m.Sitlconfig
	}
	return nil
}

func (m *CompleteMission) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

func init() {
	proto.RegisterType((*MissionName)(nil), "interop.MissionName")
	proto.RegisterType((*MissionNameList)(nil), "interop.MissionNameList")
	proto.RegisterType((*Target)(nil), "interop.Target")
	proto.RegisterType((*SitlConfig)(nil), "interop.SitlConfig")
	proto.RegisterType((*CompleteMission)(nil), "interop.CompleteMission")
}

func init() { proto.RegisterFile("interop/mission_edit.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x92, 0xbf, 0x6e, 0xdb, 0x30,
	0x10, 0xc6, 0x21, 0x3b, 0xb6, 0xa3, 0x53, 0x00, 0x39, 0xd7, 0x16, 0x15, 0x8c, 0x0e, 0xaa, 0x26,
	0x27, 0x05, 0xdc, 0xc0, 0x99, 0x3a, 0x74, 0x72, 0xc7, 0xfe, 0x01, 0xd4, 0xee, 0x06, 0x2d, 0xd1,
	0x0e, 0x11, 0x8a, 0x14, 0xc8, 0xf3, 0xd0, 0x77, 0xea, 0xd3, 0xf5, 0x09, 0x0a, 0x91, 0xfa, 0xe7,
	0x4e, 0xd9, 0x74, 0xdf, 0xf7, 0xfb, 0x4e, 0x24, 0xef, 0x60, 0x25, 0x14, 0x71, 0xa3, 0xeb, 0x8f,
	0x95, 0xb0, 0x56, 0x68, 0xb5, 0xe7, 0xa5, 0xa0, 0x4d, 0x6d, 0x34, 0x69, 0x5c, 0xb4, 0xde, 0xea,
	0x6d, 0x07, 0xe9, 0x83, 0x25, 0x56, 0x48, 0x6e, 0x3d, 0xb1, 0x7a, 0xf3, 0x5f, 0xda, 0xcb, 0xd9,
	0x03, 0x44, 0xdf, 0xbc, 0xf0, 0x9d, 0x55, 0x1c, 0xdf, 0xc3, 0x4d, 0xd7, 0x5d, 0xb1, 0x8a, 0x27,
	0x41, 0x1a, 0xac, 0xc3, 0x3c, 0xaa, 0x06, 0x24, 0xfb, 0x0c, 0xf1, 0x28, 0xf1, 0x55, 0x58, 0xc2,
	0x7b, 0xb8, 0x1d, 0xa7, 0xf6, 0x52, 0x58, 0x4a, 0x82, 0x74, 0xba, 0x0e, 0xf3, 0xb8, 0xba, 0x64,
	0xb3, 0x3f, 0x13, 0x98, 0xff, 0x62, 0xe6, 0xc4, 0x09, 0x11, 0xae, 0xe8, 0x77, 0xdd, 0xfd, 0xc4,
	0x7d, 0xe3, 0x0a, 0xae, 0x25, 0x23, 0x41, 0xe7, 0x92, 0x27, 0x93, 0x34, 0x58, 0x4f, 0xf2, 0xbe,
	0xc6, 0x77, 0x10, 0x4a, 0xad, 0x4e, 0xde, 0x9c, 0x3a, 0x73, 0x10, 0xf0, 0x35, 0xcc, 0xec, 0x13,
	0xab, 0x79, 0x72, 0xe5, 0xda, 0xf9, 0x02, 0x33, 0xb8, 0x61, 0xb2, 0x7e, 0x62, 0xea, 0x5c, 0x71,
	0x23, 0x8a, 0x64, 0xe6, 0xcc, 0x0b, 0x0d, 0x3f, 0xc0, 0x2d, 0x93, 0x75, 0x57, 0xee, 0x0b, 0x2d,
	0xb5, 0x49, 0xe6, 0x0e, 0x5c, 0x8e, 0x8c, 0x5d, 0xa3, 0xe3, 0x1d, 0x2c, 0x0f, 0xac, 0x78, 0x3e,
	0x19, 0x7d, 0x56, 0x65, 0xcb, 0x2e, 0x1c, 0x1b, 0x0f, 0xba, 0x47, 0x53, 0x88, 0x4a, 0x6e, 0x0b,
	0x23, 0x6a, 0x12, 0x5a, 0x25, 0xd7, 0xfe, 0x2d, 0x47, 0x52, 0x43, 0x68, 0x23, 0xb8, 0x22, 0xe6,
	0x88, 0xd0, 0x13, 0x23, 0x29, 0xfb, 0x04, 0xf0, 0x53, 0x90, 0xdc, 0x69, 0x75, 0x14, 0xa7, 0xe6,
	0xa4, 0xc4, 0x9e, 0xb9, 0x3e, 0x1e, 0xf7, 0xa5, 0x30, 0xbc, 0x70, 0xa9, 0xe6, 0xf9, 0x66, 0xf9,
	0xb2, 0x35, 0xbe, 0x74, 0x7a, 0xf6, 0x37, 0x80, 0x78, 0xa7, 0xab, 0x5a, 0x72, 0xe2, 0xed, 0xc4,
	0x5e, 0x30, 0x5f, 0xbc, 0x87, 0x45, 0x5b, 0xba, 0x01, 0x44, 0xdb, 0xe5, 0xa6, 0x5d, 0x9d, 0x4d,
	0xdb, 0x25, 0xef, 0x00, 0x7c, 0x80, 0xb0, 0xdf, 0x33, 0x37, 0x91, 0x68, 0x8b, 0x3d, 0xfd, 0xa3,
	0x73, 0xf2, 0x01, 0xc2, 0x47, 0x00, 0x2b, 0x48, 0x16, 0xee, 0x3e, 0x6e, 0x54, 0xd1, 0xf6, 0x55,
	0x1f, 0x19, 0xae, 0x9a, 0x8f, 0x30, 0xbc, 0x83, 0x05, 0xb9, 0x95, 0xb1, 0xc9, 0x2c, 0x9d, 0xae,
	0xa3, 0x6d, 0xdc, 0x27, 0xfc, 0x2a, 0xe5, 0x9d, 0x7f, 0x98, 0xbb, 0xb5, 0x7e, 0xfc, 0x17, 0x00,
	0x00, 0xff, 0xff, 0x7a, 0xb5, 0x6e, 0x0f, 0x2d, 0x03, 0x00, 0x00,
}
