// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interop/service.proto

package interop

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Interop service

type InteropClient interface {
	// Get active mission
	GetActiveMission(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Mission, error)
	StartServer(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type interopClient struct {
	cc *grpc.ClientConn
}

func NewInteropClient(cc *grpc.ClientConn) InteropClient {
	return &interopClient{cc}
}

func (c *interopClient) GetActiveMission(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*Mission, error) {
	out := new(Mission)
	err := grpc.Invoke(ctx, "/interop.Interop/GetActiveMission", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *interopClient) StartServer(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/interop.Interop/StartServer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Interop service

type InteropServer interface {
	// Get active mission
	GetActiveMission(context.Context, *google_protobuf1.Empty) (*Mission, error)
	StartServer(context.Context, *google_protobuf1.Empty) (*google_protobuf1.Empty, error)
}

func RegisterInteropServer(s *grpc.Server, srv InteropServer) {
	s.RegisterService(&_Interop_serviceDesc, srv)
}

func _Interop_GetActiveMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteropServer).GetActiveMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interop.Interop/GetActiveMission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteropServer).GetActiveMission(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Interop_StartServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InteropServer).StartServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interop.Interop/StartServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InteropServer).StartServer(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Interop_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interop.Interop",
	HandlerType: (*InteropServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActiveMission",
			Handler:    _Interop_GetActiveMission_Handler,
		},
		{
			MethodName: "StartServer",
			Handler:    _Interop_StartServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interop/service.proto",
}

// Client API for MissionReporting service

type MissionReportingClient interface {
	Status(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*MissionReportStatus, error)
}

type missionReportingClient struct {
	cc *grpc.ClientConn
}

func NewMissionReportingClient(cc *grpc.ClientConn) MissionReportingClient {
	return &missionReportingClient{cc}
}

func (c *missionReportingClient) Status(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*MissionReportStatus, error) {
	out := new(MissionReportStatus)
	err := grpc.Invoke(ctx, "/interop.MissionReporting/Status", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MissionReporting service

type MissionReportingServer interface {
	Status(context.Context, *google_protobuf1.Empty) (*MissionReportStatus, error)
}

func RegisterMissionReportingServer(s *grpc.Server, srv MissionReportingServer) {
	s.RegisterService(&_MissionReporting_serviceDesc, srv)
}

func _MissionReporting_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionReportingServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interop.MissionReporting/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionReportingServer).Status(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _MissionReporting_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interop.MissionReporting",
	HandlerType: (*MissionReportingServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _MissionReporting_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interop/service.proto",
}

// Client API for MissionEdit service

type MissionEditClient interface {
	GetMissionList(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*MissionNameList, error)
	GetMission(ctx context.Context, in *MissionName, opts ...grpc.CallOption) (*CompleteMission, error)
	PostMission(ctx context.Context, in *CompleteMission, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type missionEditClient struct {
	cc *grpc.ClientConn
}

func NewMissionEditClient(cc *grpc.ClientConn) MissionEditClient {
	return &missionEditClient{cc}
}

func (c *missionEditClient) GetMissionList(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*MissionNameList, error) {
	out := new(MissionNameList)
	err := grpc.Invoke(ctx, "/interop.MissionEdit/GetMissionList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionEditClient) GetMission(ctx context.Context, in *MissionName, opts ...grpc.CallOption) (*CompleteMission, error) {
	out := new(CompleteMission)
	err := grpc.Invoke(ctx, "/interop.MissionEdit/GetMission", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *missionEditClient) PostMission(ctx context.Context, in *CompleteMission, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/interop.MissionEdit/PostMission", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for MissionEdit service

type MissionEditServer interface {
	GetMissionList(context.Context, *google_protobuf1.Empty) (*MissionNameList, error)
	GetMission(context.Context, *MissionName) (*CompleteMission, error)
	PostMission(context.Context, *CompleteMission) (*google_protobuf1.Empty, error)
}

func RegisterMissionEditServer(s *grpc.Server, srv MissionEditServer) {
	s.RegisterService(&_MissionEdit_serviceDesc, srv)
}

func _MissionEdit_GetMissionList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionEditServer).GetMissionList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interop.MissionEdit/GetMissionList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionEditServer).GetMissionList(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _MissionEdit_GetMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MissionName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionEditServer).GetMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interop.MissionEdit/GetMission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionEditServer).GetMission(ctx, req.(*MissionName))
	}
	return interceptor(ctx, in, info, handler)
}

func _MissionEdit_PostMission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MissionEditServer).PostMission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interop.MissionEdit/PostMission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MissionEditServer).PostMission(ctx, req.(*CompleteMission))
	}
	return interceptor(ctx, in, info, handler)
}

var _MissionEdit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interop.MissionEdit",
	HandlerType: (*MissionEditServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMissionList",
			Handler:    _MissionEdit_GetMissionList_Handler,
		},
		{
			MethodName: "GetMission",
			Handler:    _MissionEdit_GetMission_Handler,
		},
		{
			MethodName: "PostMission",
			Handler:    _MissionEdit_PostMission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interop/service.proto",
}

func init() { proto.RegisterFile("interop/service.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0x33, 0x31,
	0x10, 0xc7, 0x69, 0x0f, 0x2d, 0xa4, 0xf0, 0x51, 0xe6, 0x6b, 0x45, 0xb6, 0x2b, 0xc2, 0x82, 0x22,
	0x0a, 0x1b, 0x5a, 0x6f, 0xde, 0x44, 0x4a, 0x11, 0x54, 0xc4, 0x9e, 0x7a, 0x92, 0x6d, 0x3b, 0x96,
	0x40, 0x77, 0xb3, 0x24, 0xd3, 0x05, 0x11, 0x2f, 0xbe, 0x82, 0x0f, 0xe4, 0x43, 0x78, 0xf3, 0xec,
	0x83, 0xc8, 0x26, 0x69, 0x2d, 0x4b, 0x03, 0x1e, 0x33, 0x33, 0xbf, 0xff, 0x6f, 0xc2, 0xb0, 0xae,
	0xc8, 0x08, 0x95, 0xcc, 0xb9, 0x46, 0x55, 0x88, 0x19, 0xc6, 0xb9, 0x92, 0x24, 0xa1, 0xe9, 0xca,
	0x41, 0xb8, 0x90, 0x72, 0xb1, 0x44, 0x9e, 0xe4, 0x82, 0x27, 0x59, 0x26, 0x29, 0x21, 0x21, 0x33,
	0x6d, 0xc7, 0x82, 0x0d, 0x9d, 0x0a, 0xad, 0x85, 0xcc, 0x5c, 0x39, 0xa8, 0x94, 0x1f, 0x71, 0x2e,
	0xc8, 0xf5, 0xc2, 0x6a, 0x4f, 0x61, 0x2e, 0xd5, 0xba, 0xdb, 0x73, 0x3a, 0xf3, 0x9a, 0xae, 0x9e,
	0x38, 0xa6, 0x39, 0x3d, 0xdb, 0xe6, 0xe0, 0xa3, 0xc6, 0x9a, 0xd7, 0x96, 0x86, 0x09, 0x6b, 0x8f,
	0x90, 0x2e, 0x67, 0x24, 0x0a, 0xbc, 0xb5, 0x49, 0xb0, 0x17, 0x5b, 0x3a, 0x5e, 0xd3, 0xf1, 0xb0,
	0xa4, 0x83, 0x76, 0xec, 0x9c, 0xb1, 0x9b, 0x8c, 0x7a, 0x6f, 0x9f, 0xdf, 0xef, 0xf5, 0x2e, 0xfc,
	0xe7, 0x45, 0x9f, 0x57, 0x16, 0x82, 0x09, 0x6b, 0x8d, 0x29, 0x51, 0x34, 0x46, 0x55, 0xa0, 0xf2,
	0xa6, 0x7a, 0xea, 0x51, 0x60, 0xb2, 0x3b, 0x00, 0xdb, 0xd9, 0xda, 0x64, 0x0d, 0x0a, 0xd6, 0x76,
	0x2b, 0x3c, 0x98, 0x5f, 0x8b, 0x6c, 0x01, 0x53, 0xd6, 0x18, 0x53, 0x42, 0x2b, 0xed, 0x35, 0x85,
	0xd5, 0xfd, 0x2d, 0x6c, 0xa9, 0x28, 0x32, 0xbe, 0x10, 0x82, 0x1d, 0x7f, 0xe1, 0xda, 0xcc, 0x0c,
	0xbe, 0xea, 0xac, 0xe5, 0xd8, 0xe1, 0x5c, 0x10, 0x08, 0xf6, 0x6f, 0x84, 0xe4, 0x2a, 0x37, 0x42,
	0x93, 0xd7, 0xbd, 0x5f, 0x75, 0xdf, 0x25, 0x29, 0x96, 0x44, 0x74, 0x64, 0xbc, 0x87, 0x70, 0x50,
	0x7a, 0x9d, 0xaf, 0xbc, 0xf3, 0xe6, 0xb0, 0x59, 0x92, 0xa2, 0x86, 0x25, 0x63, 0xbf, 0x2a, 0xe8,
	0xec, 0x8a, 0xdb, 0x92, 0x5c, 0xc9, 0x34, 0x5f, 0x22, 0xad, 0x4f, 0x1a, 0xc5, 0x46, 0x72, 0x02,
	0xc7, 0x1e, 0x09, 0x7f, 0xd9, 0xb6, 0xbd, 0x82, 0x62, 0xad, 0x7b, 0xa9, 0x37, 0x3a, 0x6f, 0xb0,
	0xf7, 0x7a, 0x7d, 0x23, 0x3c, 0x8b, 0xfe, 0x28, 0xbc, 0xa8, 0x9d, 0x4e, 0x1b, 0x26, 0xe2, 0xfc,
	0x27, 0x00, 0x00, 0xff, 0xff, 0x85, 0x56, 0x1b, 0xe5, 0x4b, 0x03, 0x00, 0x00,
}
