name: Docker

on:
  push:
    # only run rebuild docker image for changes to master
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Build and Push hub
  hub:
    name: dockerhub build
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v2
      -
        name: clone submodule
        uses: actions/checkout@v2
        with:
          repository: tritonuas/protos
          path: protos
          token: ${{ secrets.SSH_TOKEN }}
          persist-credentials: true
      -
        name: checkout submodule
        run: |
          git submodule init
          git submodule update
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      -
        name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: build/package/Dockerfile
          push: true
          tags: |
            tritonuas/hub:latest
            ghcr.io/tritonuas/hub:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.GITHUB_TOKEN }}
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
