name: Docker

on:
  push:
    # only run rebuild docker image for changes to master
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Build and Push hub
  hub:
    name: dockerhub build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Build and Push to dockerhub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          build_args: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          repository: tritonuas/hub
