---
name: Linting

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure git for private modules
        env:
          ACCOUNT: ${{ secrets.GITHUB_ACCOUNT_USER }}
          TOKEN: ${{ secrets.GITHUB_ACCOUNT_TOKEN }}
        run: git config --global url."https://${ACCOUNT}:${TOKEN}@github.com".insteadOf "https://github.com

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
