---
name: Linting

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.SSH_TOKEN }}

      - name: Install dependencies
        run: make install-dependencies

      - name: Build Protos
        run: make build-protos

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59.1

  eslint:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Frontend Linter
        run: |
          cd houston
          npm install
          npm run lint
