---
name: Linting

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.x"

      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.SSH_TOKEN }}

      - name: Install dependencies
        run: make install-dependencies

      - name: Build Protos
        run: make build-protos

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7

  eslint:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install root deps (Prettier)
        run: npm ci
      - name: Install frontend deps
        run: npm ci --prefix houston
      - name: Prettier Check
        run: npm run format:check
      - name: Run Frontend Linter
        run: npm run --prefix houston lint
