name: Linting

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # Dockerfile linting
  dockerfile:
    name: Dockerfile dockerfilelint
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install dockerfilelint
        run: npm install -g dockerfilelint
      - name: Lint Dockerfile
        run: dockerfilelint Dockerfile

  # Go linting
  go:
    name: Go golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Lint Go
        uses: golangci/golangci-lint-action@v1
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.29


  # Markdown linting
  markdown:
    name: Markdown markdownlint
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install markdown-lint-cli
        run: npm install -g markdownlint-cli
      - name: Lint Markdown
        run: markdownlint **/*.md

  # Shell checks
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install shellcheck
        run: sudo apt install shellcheck
      - name: Run shellcheck
        run: shellcheck scripts/*

  # yaml linting
  yaml:
    name: Yaml yamllint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Lint Yaml
        uses: ibiqlik/action-yamllint@v1
