name: Tests

on:
  push:
  pull_request:

jobs:
  # go tests
  gotest:
    name: Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.SSH_TOKEN }}

      - name: Install dependencies
        run: make install-dependencies

      - name: Test
        run: |
          go test -race ./...

  Jest:
    name: Test Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run: |
          cd houston
          npm install 
          npm test
