name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # go tests
  gotest:
    name: Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install libzmq
        run: sudo apt-get -y install libzmq3-dev
      - name: Test
        run: go test ./...
