name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  # go tests
  gotest:
    name: Go tests
    runs-on: ubuntu-latest

    steps:
      -
        name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      -
        name: Checkout Repo
        uses: actions/checkout@v2
      -
        name: clone submodule
        uses: actions/checkout@v2
        with:
          repository: tritonuas/protos
          path: protos
          token: ${{ secrets.SSH_TOKEN }}
          persist-credentials: true
      -
        name: checkout submodule
        run: |
          git submodule init
          git submodule update
      -
        name: Install libzmq
        run: |
          sudo apt update
          sudo apt install -y libzmq3-dev
      -
        name: Install dependencies
        run: make install-dependencies
      -
        name: Compile protobufs
        run: make compile-protobufs
      -
        name: Test
        run: make test
