name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  # go tests
  gotest:
    name: Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.SSH_TOKEN }}

      - name: Install dependencies
        run: make install-dependencies

      - name: Test
        run: make test
